# Generated by Django 5.0.14 on 2026-08-19 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_rename_content_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('meta_category', models.CharField(default='web app · api', help_text='e.g. web app · api', max_length=100)),
                ('description', models.TextField()),
                ('tech_tags', models.CharField(help_text='Comma-separated tags, e.g. Django, HTML, HTMX, CSS', max_length=250)),
                ('browser_url', models.CharField(help_text='Display URL in browser bar, e.g. django-blog-api-292e.onrender.com', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Upload preview image', null=True, upload_to='images/')),
                ('image_static_path', models.CharField(blank=True, help_text='Or static image path, e.g. images/blog.png', max_length=200, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_role', models.CharField(default='Full Stack Developer', max_length=150)),
                ('hero_role_text', models.CharField(default='builds reliable web apps with Django, Python & HTMX', max_length=250)),
                ('status_message', models.CharField(default="open to new projects | let's build something worth shipping.", max_length=250)),
                ('availability', models.CharField(default='Available for new projects', max_length=150)),
                ('location', models.CharField(default='Nigeria · UTC+1 · remote friendly', max_length=150)),
                ('bio_p1', models.TextField(default="I'm a full-stack developer who loves solving real problems with code. Using tools like Django, Python and JavaScript, I build efficient, modern web applications with clean design and solid performance.")),
                ('bio_p2', models.TextField(default='I focus on delivering real-world solutions that are reliable, easy to use and built to scale, from API backends to Dockerised deployments.')),
                ('email', models.EmailField(default='emmyadeoluwa@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+234 907 360 1282', max_length=50)),
                ('twitter_url', models.URLField(default='https://x.com/Emidveloper')),
                ('github_url', models.URLField(default='https://github.com/Eminenz07')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Data & AI', 'Data & AI'), ('Infra & DevOps', 'Infra & DevOps')], default='Backend', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], default='Intermediate', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
